package config

object Size {

    const val APPLICATION_WIDTH = 1280.0
    const val APPLICAITON_HEIGHT = 720.0

    const val MAIN_FUNCITON_LIST_WIDTH = 260.0
    const val MAIN_CONTENT_WIDTH = APPLICATION_WIDTH - MAIN_FUNCITON_LIST_WIDTH

    const val STATISTIC_PADDING = 16.0
    const val STATISTIC_WIDTH = MAIN_CONTENT_WIDTH - STATISTIC_PADDING * 2
    const val STATISTIC_HEIGHT = STATISTIC_WIDTH
    const val STATISTIC_PATH_PADDING_TOP = 16.0
    const val STATISTIC_PATH_LABEL_WIDTH = 82.0
    const val STATISTIC_PATH_BUTTON_WIDTH = 120.0
    const val STATISTIC_PATH_TEXT_AREA_WIDTH = STATISTIC_WIDTH - STATISTIC_PATH_LABEL_WIDTH - STATISTIC_PATH_BUTTON_WIDTH * 2
    const val STATISTIC_STATISTIC_TOP = 16.0
}